### ISSUE TITLE
 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

### ISSUE THREAD

**Issue by xzakier** [DyonR/docker-qbittorrentvpn#169] opened 2023-03-29 10:21 UTC
2023-03-29 10:18:58 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
2023-03-29 10:18:58 Exiting due to fatal error

**Comment by itsmexxie** [comment] 2023-03-31 21:20
**DUPLICATE OF #39** 

Add `--device=/dev/net/tun` to your run arguments.
Or add this to your docker-compose.yml file if you're using that:
```
devices:
    - /dev/net/tun
```

**Closed as completed** 2023-04-02 14:24 UTC
